/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.threatModelLanguage.AddFlow;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Flow</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.AddFlowImpl#getSourceId <em>Source Id</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.AddFlowImpl#getDestinationId <em>Destination Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AddFlowImpl extends AddImpl implements AddFlow
{
  /**
   * The default value of the '{@link #getSourceId() <em>Source Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceId()
   * @generated
   * @ordered
   */
  protected static final String SOURCE_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSourceId() <em>Source Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceId()
   * @generated
   * @ordered
   */
  protected String sourceId = SOURCE_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getDestinationId() <em>Destination Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestinationId()
   * @generated
   * @ordered
   */
  protected static final String DESTINATION_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDestinationId() <em>Destination Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestinationId()
   * @generated
   * @ordered
   */
  protected String destinationId = DESTINATION_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddFlowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.ADD_FLOW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSourceId()
  {
    return sourceId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceId(String newSourceId)
  {
    String oldSourceId = sourceId;
    sourceId = newSourceId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.ADD_FLOW__SOURCE_ID, oldSourceId, sourceId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDestinationId()
  {
    return destinationId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDestinationId(String newDestinationId)
  {
    String oldDestinationId = destinationId;
    destinationId = newDestinationId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.ADD_FLOW__DESTINATION_ID, oldDestinationId, destinationId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.ADD_FLOW__SOURCE_ID:
        return getSourceId();
      case ThreatModelLanguagePackage.ADD_FLOW__DESTINATION_ID:
        return getDestinationId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.ADD_FLOW__SOURCE_ID:
        setSourceId((String)newValue);
        return;
      case ThreatModelLanguagePackage.ADD_FLOW__DESTINATION_ID:
        setDestinationId((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.ADD_FLOW__SOURCE_ID:
        setSourceId(SOURCE_ID_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.ADD_FLOW__DESTINATION_ID:
        setDestinationId(DESTINATION_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.ADD_FLOW__SOURCE_ID:
        return SOURCE_ID_EDEFAULT == null ? sourceId != null : !SOURCE_ID_EDEFAULT.equals(sourceId);
      case ThreatModelLanguagePackage.ADD_FLOW__DESTINATION_ID:
        return DESTINATION_ID_EDEFAULT == null ? destinationId != null : !DESTINATION_ID_EDEFAULT.equals(destinationId);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sourceId: ");
    result.append(sourceId);
    result.append(", destinationId: ");
    result.append(destinationId);
    result.append(')');
    return result.toString();
  }

} //AddFlowImpl
