/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.AddProcess;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AddProcessImpl extends AddEntityImpl implements AddProcess
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.ADD_PROCESS;
  }

} //AddProcessImpl
