/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.threatModelLanguage.BoundaryAddEntity;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boundary Add Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.BoundaryAddEntityImpl#getNewEntity <em>New Entity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BoundaryAddEntityImpl extends ModifyImpl implements BoundaryAddEntity
{
  /**
   * The default value of the '{@link #getNewEntity() <em>New Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNewEntity()
   * @generated
   * @ordered
   */
  protected static final String NEW_ENTITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNewEntity() <em>New Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNewEntity()
   * @generated
   * @ordered
   */
  protected String newEntity = NEW_ENTITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoundaryAddEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.BOUNDARY_ADD_ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNewEntity()
  {
    return newEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNewEntity(String newNewEntity)
  {
    String oldNewEntity = newEntity;
    newEntity = newNewEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.BOUNDARY_ADD_ENTITY__NEW_ENTITY, oldNewEntity, newEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_ADD_ENTITY__NEW_ENTITY:
        return getNewEntity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_ADD_ENTITY__NEW_ENTITY:
        setNewEntity((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_ADD_ENTITY__NEW_ENTITY:
        setNewEntity(NEW_ENTITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_ADD_ENTITY__NEW_ENTITY:
        return NEW_ENTITY_EDEFAULT == null ? newEntity != null : !NEW_ENTITY_EDEFAULT.equals(newEntity);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (newEntity: ");
    result.append(newEntity);
    result.append(')');
    return result.toString();
  }

} //BoundaryAddEntityImpl
