/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.threatModelLanguage.BoundaryRemoveEntity;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boundary Remove Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.BoundaryRemoveEntityImpl#getOldEntity <em>Old Entity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BoundaryRemoveEntityImpl extends ModifyImpl implements BoundaryRemoveEntity
{
  /**
   * The default value of the '{@link #getOldEntity() <em>Old Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOldEntity()
   * @generated
   * @ordered
   */
  protected static final String OLD_ENTITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOldEntity() <em>Old Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOldEntity()
   * @generated
   * @ordered
   */
  protected String oldEntity = OLD_ENTITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoundaryRemoveEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.BOUNDARY_REMOVE_ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOldEntity()
  {
    return oldEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOldEntity(String newOldEntity)
  {
    String oldOldEntity = oldEntity;
    oldEntity = newOldEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.BOUNDARY_REMOVE_ENTITY__OLD_ENTITY, oldOldEntity, oldEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_REMOVE_ENTITY__OLD_ENTITY:
        return getOldEntity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_REMOVE_ENTITY__OLD_ENTITY:
        setOldEntity((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_REMOVE_ENTITY__OLD_ENTITY:
        setOldEntity(OLD_ENTITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.BOUNDARY_REMOVE_ENTITY__OLD_ENTITY:
        return OLD_ENTITY_EDEFAULT == null ? oldEntity != null : !OLD_ENTITY_EDEFAULT.equals(oldEntity);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (oldEntity: ");
    result.append(oldEntity);
    result.append(')');
    return result.toString();
  }

} //BoundaryRemoveEntityImpl
