/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.Countermeasure;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Countermeasure</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CountermeasureImpl extends GroupingImpl implements Countermeasure
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CountermeasureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.COUNTERMEASURE;
  }

} //CountermeasureImpl
