/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.Datastore;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DatastoreImpl extends EntityImpl implements Datastore
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DatastoreImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.DATASTORE;
  }

} //DatastoreImpl
