/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.threatModelLanguage.FlowFix;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Flow Fix</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.FlowFixImpl#getFlowId <em>Flow Id</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.FlowFixImpl#getEntityId <em>Entity Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FlowFixImpl extends MinimalEObjectImpl.Container implements FlowFix
{
  /**
   * The default value of the '{@link #getFlowId() <em>Flow Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlowId()
   * @generated
   * @ordered
   */
  protected static final String FLOW_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFlowId() <em>Flow Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlowId()
   * @generated
   * @ordered
   */
  protected String flowId = FLOW_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getEntityId() <em>Entity Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityId()
   * @generated
   * @ordered
   */
  protected static final String ENTITY_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntityId() <em>Entity Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityId()
   * @generated
   * @ordered
   */
  protected String entityId = ENTITY_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FlowFixImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.FLOW_FIX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFlowId()
  {
    return flowId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFlowId(String newFlowId)
  {
    String oldFlowId = flowId;
    flowId = newFlowId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.FLOW_FIX__FLOW_ID, oldFlowId, flowId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntityId()
  {
    return entityId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntityId(String newEntityId)
  {
    String oldEntityId = entityId;
    entityId = newEntityId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.FLOW_FIX__ENTITY_ID, oldEntityId, entityId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.FLOW_FIX__FLOW_ID:
        return getFlowId();
      case ThreatModelLanguagePackage.FLOW_FIX__ENTITY_ID:
        return getEntityId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.FLOW_FIX__FLOW_ID:
        setFlowId((String)newValue);
        return;
      case ThreatModelLanguagePackage.FLOW_FIX__ENTITY_ID:
        setEntityId((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.FLOW_FIX__FLOW_ID:
        setFlowId(FLOW_ID_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.FLOW_FIX__ENTITY_ID:
        setEntityId(ENTITY_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.FLOW_FIX__FLOW_ID:
        return FLOW_ID_EDEFAULT == null ? flowId != null : !FLOW_ID_EDEFAULT.equals(flowId);
      case ThreatModelLanguagePackage.FLOW_FIX__ENTITY_ID:
        return ENTITY_ID_EDEFAULT == null ? entityId != null : !ENTITY_ID_EDEFAULT.equals(entityId);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (flowId: ");
    result.append(flowId);
    result.append(", entityId: ");
    result.append(entityId);
    result.append(')');
    return result.toString();
  }

} //FlowFixImpl
