/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.threatModelLanguage.MergeEntity;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Merge Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.MergeEntityImpl#getEntity1 <em>Entity1</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.MergeEntityImpl#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.MergeEntityImpl#getName <em>Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.MergeEntityImpl#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MergeEntityImpl extends ModifyImpl implements MergeEntity
{
  /**
   * The default value of the '{@link #getEntity1() <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1()
   * @generated
   * @ordered
   */
  protected static final String ENTITY1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity1() <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1()
   * @generated
   * @ordered
   */
  protected String entity1 = ENTITY1_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity2() <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2()
   * @generated
   * @ordered
   */
  protected static final String ENTITY2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity2() <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2()
   * @generated
   * @ordered
   */
  protected String entity2 = ENTITY2_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MergeEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.MERGE_ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity1()
  {
    return entity1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity1(String newEntity1)
  {
    String oldEntity1 = entity1;
    entity1 = newEntity1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY1, oldEntity1, entity1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity2()
  {
    return entity2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity2(String newEntity2)
  {
    String oldEntity2 = entity2;
    entity2 = newEntity2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY2, oldEntity2, entity2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.MERGE_ENTITY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.MERGE_ENTITY__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY1:
        return getEntity1();
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY2:
        return getEntity2();
      case ThreatModelLanguagePackage.MERGE_ENTITY__NAME:
        return getName();
      case ThreatModelLanguagePackage.MERGE_ENTITY__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY1:
        setEntity1((String)newValue);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY2:
        setEntity2((String)newValue);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__NAME:
        setName((String)newValue);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__DESCRIPTION:
        setDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY1:
        setEntity1(ENTITY1_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY2:
        setEntity2(ENTITY2_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.MERGE_ENTITY__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY1:
        return ENTITY1_EDEFAULT == null ? entity1 != null : !ENTITY1_EDEFAULT.equals(entity1);
      case ThreatModelLanguagePackage.MERGE_ENTITY__ENTITY2:
        return ENTITY2_EDEFAULT == null ? entity2 != null : !ENTITY2_EDEFAULT.equals(entity2);
      case ThreatModelLanguagePackage.MERGE_ENTITY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ThreatModelLanguagePackage.MERGE_ENTITY__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (entity1: ");
    result.append(entity1);
    result.append(", entity2: ");
    result.append(entity2);
    result.append(", name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //MergeEntityImpl
