/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.MergeIntoDatastore;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Merge Into Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MergeIntoDatastoreImpl extends MergeEntityImpl implements MergeIntoDatastore
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MergeIntoDatastoreImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.MERGE_INTO_DATASTORE;
  }

} //MergeIntoDatastoreImpl
