/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.SplitDatastoreAndDatastore;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Split Datastore And Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SplitDatastoreAndDatastoreImpl extends SplitEntityImpl implements SplitDatastoreAndDatastore
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitDatastoreAndDatastoreImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLIT_DATASTORE_AND_DATASTORE;
  }

} //SplitDatastoreAndDatastoreImpl
