/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.SplitExternalAndProcess;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Split External And Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SplitExternalAndProcessImpl extends SplitEntityImpl implements SplitExternalAndProcess
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitExternalAndProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLIT_EXTERNAL_AND_PROCESS;
  }

} //SplitExternalAndProcessImpl
