/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.SplitProcessAndProcess;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Split Process And Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SplitProcessAndProcessImpl extends SplitEntityImpl implements SplitProcessAndProcess
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitProcessAndProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLIT_PROCESS_AND_PROCESS;
  }

} //SplitProcessAndProcessImpl
