/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.SplitProcessAndExternal;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Split Process And External</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SplitProcessAndExternalImpl extends SplitEntityImpl implements SplitProcessAndExternal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitProcessAndExternalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLIT_PROCESS_AND_EXTERNAL;
  }

} //SplitProcessAndExternalImpl
