/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.threatModelLanguage.SplitsDatastoreAndProcess;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Splits Datastore And Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SplitsDatastoreAndProcessImpl extends SplitEntityImpl implements SplitsDatastoreAndProcess
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitsDatastoreAndProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLITS_DATASTORE_AND_PROCESS;
  }

} //SplitsDatastoreAndProcessImpl
