/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.threatModelLanguage.FlowFix;
import xtext.threatModelLanguage.SplitEntity;
import xtext.threatModelLanguage.ThreatModelLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Split Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity1 <em>Entity1</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity1Name <em>Entity1 Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity1Description <em>Entity1 Description</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity2Name <em>Entity2 Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getEntity2Description <em>Entity2 Description</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.impl.SplitEntityImpl#getFlowFix <em>Flow Fix</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SplitEntityImpl extends ModifyImpl implements SplitEntity
{
  /**
   * The default value of the '{@link #getEntity1() <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1()
   * @generated
   * @ordered
   */
  protected static final String ENTITY1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity1() <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1()
   * @generated
   * @ordered
   */
  protected String entity1 = ENTITY1_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity1Name() <em>Entity1 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1Name()
   * @generated
   * @ordered
   */
  protected static final String ENTITY1_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity1Name() <em>Entity1 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1Name()
   * @generated
   * @ordered
   */
  protected String entity1Name = ENTITY1_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity1Description() <em>Entity1 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1Description()
   * @generated
   * @ordered
   */
  protected static final String ENTITY1_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity1Description() <em>Entity1 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity1Description()
   * @generated
   * @ordered
   */
  protected String entity1Description = ENTITY1_DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity2() <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2()
   * @generated
   * @ordered
   */
  protected static final String ENTITY2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity2() <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2()
   * @generated
   * @ordered
   */
  protected String entity2 = ENTITY2_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity2Name() <em>Entity2 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2Name()
   * @generated
   * @ordered
   */
  protected static final String ENTITY2_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity2Name() <em>Entity2 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2Name()
   * @generated
   * @ordered
   */
  protected String entity2Name = ENTITY2_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getEntity2Description() <em>Entity2 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2Description()
   * @generated
   * @ordered
   */
  protected static final String ENTITY2_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntity2Description() <em>Entity2 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity2Description()
   * @generated
   * @ordered
   */
  protected String entity2Description = ENTITY2_DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getFlowFix() <em>Flow Fix</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlowFix()
   * @generated
   * @ordered
   */
  protected EList<FlowFix> flowFix;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SplitEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThreatModelLanguagePackage.Literals.SPLIT_ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity1()
  {
    return entity1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity1(String newEntity1)
  {
    String oldEntity1 = entity1;
    entity1 = newEntity1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1, oldEntity1, entity1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity1Name()
  {
    return entity1Name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity1Name(String newEntity1Name)
  {
    String oldEntity1Name = entity1Name;
    entity1Name = newEntity1Name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_NAME, oldEntity1Name, entity1Name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity1Description()
  {
    return entity1Description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity1Description(String newEntity1Description)
  {
    String oldEntity1Description = entity1Description;
    entity1Description = newEntity1Description;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_DESCRIPTION, oldEntity1Description, entity1Description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity2()
  {
    return entity2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity2(String newEntity2)
  {
    String oldEntity2 = entity2;
    entity2 = newEntity2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2, oldEntity2, entity2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity2Name()
  {
    return entity2Name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity2Name(String newEntity2Name)
  {
    String oldEntity2Name = entity2Name;
    entity2Name = newEntity2Name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_NAME, oldEntity2Name, entity2Name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntity2Description()
  {
    return entity2Description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity2Description(String newEntity2Description)
  {
    String oldEntity2Description = entity2Description;
    entity2Description = newEntity2Description;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_DESCRIPTION, oldEntity2Description, entity2Description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FlowFix> getFlowFix()
  {
    if (flowFix == null)
    {
      flowFix = new EObjectContainmentEList<FlowFix>(FlowFix.class, this, ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX);
    }
    return flowFix;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX:
        return ((InternalEList<?>)getFlowFix()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1:
        return getEntity1();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_NAME:
        return getEntity1Name();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_DESCRIPTION:
        return getEntity1Description();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2:
        return getEntity2();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_NAME:
        return getEntity2Name();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_DESCRIPTION:
        return getEntity2Description();
      case ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX:
        return getFlowFix();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1:
        setEntity1((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_NAME:
        setEntity1Name((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_DESCRIPTION:
        setEntity1Description((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2:
        setEntity2((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_NAME:
        setEntity2Name((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_DESCRIPTION:
        setEntity2Description((String)newValue);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX:
        getFlowFix().clear();
        getFlowFix().addAll((Collection<? extends FlowFix>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1:
        setEntity1(ENTITY1_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_NAME:
        setEntity1Name(ENTITY1_NAME_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_DESCRIPTION:
        setEntity1Description(ENTITY1_DESCRIPTION_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2:
        setEntity2(ENTITY2_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_NAME:
        setEntity2Name(ENTITY2_NAME_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_DESCRIPTION:
        setEntity2Description(ENTITY2_DESCRIPTION_EDEFAULT);
        return;
      case ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX:
        getFlowFix().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1:
        return ENTITY1_EDEFAULT == null ? entity1 != null : !ENTITY1_EDEFAULT.equals(entity1);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_NAME:
        return ENTITY1_NAME_EDEFAULT == null ? entity1Name != null : !ENTITY1_NAME_EDEFAULT.equals(entity1Name);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY1_DESCRIPTION:
        return ENTITY1_DESCRIPTION_EDEFAULT == null ? entity1Description != null : !ENTITY1_DESCRIPTION_EDEFAULT.equals(entity1Description);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2:
        return ENTITY2_EDEFAULT == null ? entity2 != null : !ENTITY2_EDEFAULT.equals(entity2);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_NAME:
        return ENTITY2_NAME_EDEFAULT == null ? entity2Name != null : !ENTITY2_NAME_EDEFAULT.equals(entity2Name);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__ENTITY2_DESCRIPTION:
        return ENTITY2_DESCRIPTION_EDEFAULT == null ? entity2Description != null : !ENTITY2_DESCRIPTION_EDEFAULT.equals(entity2Description);
      case ThreatModelLanguagePackage.SPLIT_ENTITY__FLOW_FIX:
        return flowFix != null && !flowFix.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (entity1: ");
    result.append(entity1);
    result.append(", entity1Name: ");
    result.append(entity1Name);
    result.append(", entity1Description: ");
    result.append(entity1Description);
    result.append(", entity2: ");
    result.append(entity2);
    result.append(", entity2Name: ");
    result.append(entity2Name);
    result.append(", entity2Description: ");
    result.append(entity2Description);
    result.append(')');
    return result.toString();
  }

} //SplitEntityImpl
