/**
 * generated by Xtext 2.33.0
 */
package xtext.generator;

import com.google.common.collect.Iterables;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import xtext.generator.backend.DSLHandler;
import xtext.generator.backend.GraphicDFD;
import xtext.generator.backend.TextualDFD;
import xtext.generator.backend.domain.Element;
import xtext.threatModelLanguage.Operations;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ThreatModelLanguageGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    DSLHandler handler = new DSLHandler();
    TextualDFD printer = new TextualDFD();
    GraphicDFD dfd = new GraphicDFD();
    String content = "#######\n";
    String _content = content;
    content = (_content + "##DFD##\n");
    String _content_1 = content;
    content = (_content_1 + "#######\n\n");
    String dot = "";
    try {
      List<Element> elements = handler.handleDSLFile(Iterables.<Operations>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Operations.class));
      String _content_2 = content;
      String _printTextualDFD = printer.printTextualDFD(elements);
      content = (_content_2 + _printTextualDFD);
      String _dot = dot;
      String _printDot = printer.printDot(elements);
      dot = (_dot + _printDot);
    } catch (final Throwable _t) {
      if (_t instanceof Exception) {
        final Exception ex = (Exception)_t;
        String _content_3 = content;
        content = (_content_3 + "There was an exception with following message: \n");
        String _content_4 = content;
        String _message = ex.getMessage();
        content = (_content_4 + _message);
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
    fsa.generateFile("demo.txt", content);
    fsa.generateFile("dfd.dot", dot);
    printer.printPNG();
  }
}
