/*
 * generated by Xtext 2.33.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractThreatModelLanguageScopeProvider extends DelegatingScopeProvider {
}
