/*
 * generated by Xtext 2.33.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ThreatModelLanguageUiModule extends AbstractThreatModelLanguageUiModule {

	public ThreatModelLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
