/*
 * generated by Xtext 2.33.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtext.threatmodel.ui.internal.ThreatmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ThreatModelLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ThreatmodelActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ThreatmodelActivator activator = ThreatmodelActivator.getInstance();
		return activator != null ? activator.getInjector(ThreatmodelActivator.XTEXT_THREATMODELLANGUAGE) : null;
	}

}
