/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Boundary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.AddBoundary#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getAddBoundary()
 * @model
 * @generated
 */
public interface AddBoundary extends Add
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' attribute list.
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getAddBoundary_Entities()
   * @model unique="false"
   * @generated
   */
  EList<String> getEntities();

} // AddBoundary
