/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Flow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.AddFlow#getSourceId <em>Source Id</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.AddFlow#getDestinationId <em>Destination Id</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getAddFlow()
 * @model
 * @generated
 */
public interface AddFlow extends Add
{
  /**
   * Returns the value of the '<em><b>Source Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Id</em>' attribute.
   * @see #setSourceId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getAddFlow_SourceId()
   * @model
   * @generated
   */
  String getSourceId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.AddFlow#getSourceId <em>Source Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Id</em>' attribute.
   * @see #getSourceId()
   * @generated
   */
  void setSourceId(String value);

  /**
   * Returns the value of the '<em><b>Destination Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination Id</em>' attribute.
   * @see #setDestinationId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getAddFlow_DestinationId()
   * @model
   * @generated
   */
  String getDestinationId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.AddFlow#getDestinationId <em>Destination Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination Id</em>' attribute.
   * @see #getDestinationId()
   * @generated
   */
  void setDestinationId(String value);

} // AddFlow
