/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boundary Add Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.BoundaryAddEntity#getNewEntity <em>New Entity</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getBoundaryAddEntity()
 * @model
 * @generated
 */
public interface BoundaryAddEntity extends Modify
{
  /**
   * Returns the value of the '<em><b>New Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Entity</em>' attribute.
   * @see #setNewEntity(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getBoundaryAddEntity_NewEntity()
   * @model
   * @generated
   */
  String getNewEntity();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.BoundaryAddEntity#getNewEntity <em>New Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Entity</em>' attribute.
   * @see #getNewEntity()
   * @generated
   */
  void setNewEntity(String value);

} // BoundaryAddEntity
