/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boundary Remove Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.BoundaryRemoveEntity#getOldEntity <em>Old Entity</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getBoundaryRemoveEntity()
 * @model
 * @generated
 */
public interface BoundaryRemoveEntity extends Modify
{
  /**
   * Returns the value of the '<em><b>Old Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Old Entity</em>' attribute.
   * @see #setOldEntity(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getBoundaryRemoveEntity_OldEntity()
   * @model
   * @generated
   */
  String getOldEntity();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.BoundaryRemoveEntity#getOldEntity <em>Old Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Old Entity</em>' attribute.
   * @see #getOldEntity()
   * @generated
   */
  void setOldEntity(String value);

} // BoundaryRemoveEntity
