/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getDatastore()
 * @model
 * @generated
 */
public interface Datastore extends Entity
{
} // Datastore
