/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flow Fix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.FlowFix#getFlowId <em>Flow Id</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.FlowFix#getEntityId <em>Entity Id</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getFlowFix()
 * @model
 * @generated
 */
public interface FlowFix extends EObject
{
  /**
   * Returns the value of the '<em><b>Flow Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flow Id</em>' attribute.
   * @see #setFlowId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getFlowFix_FlowId()
   * @model
   * @generated
   */
  String getFlowId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.FlowFix#getFlowId <em>Flow Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flow Id</em>' attribute.
   * @see #getFlowId()
   * @generated
   */
  void setFlowId(String value);

  /**
   * Returns the value of the '<em><b>Entity Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Id</em>' attribute.
   * @see #setEntityId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getFlowFix_EntityId()
   * @model
   * @generated
   */
  String getEntityId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.FlowFix#getEntityId <em>Entity Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Id</em>' attribute.
   * @see #getEntityId()
   * @generated
   */
  void setEntityId(String value);

} // FlowFix
