/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Into Process</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeIntoProcess()
 * @model
 * @generated
 */
public interface MergeIntoProcess extends MergeEntity
{
} // MergeIntoProcess
