/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.MergeEntity#getEntity1 <em>Entity1</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.MergeEntity#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.MergeEntity#getName <em>Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.MergeEntity#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeEntity()
 * @model
 * @generated
 */
public interface MergeEntity extends Modify
{
  /**
   * Returns the value of the '<em><b>Entity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity1</em>' attribute.
   * @see #setEntity1(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeEntity_Entity1()
   * @model
   * @generated
   */
  String getEntity1();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.MergeEntity#getEntity1 <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity1</em>' attribute.
   * @see #getEntity1()
   * @generated
   */
  void setEntity1(String value);

  /**
   * Returns the value of the '<em><b>Entity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2</em>' attribute.
   * @see #setEntity2(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeEntity_Entity2()
   * @model
   * @generated
   */
  String getEntity2();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.MergeEntity#getEntity2 <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2</em>' attribute.
   * @see #getEntity2()
   * @generated
   */
  void setEntity2(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.MergeEntity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeEntity_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.MergeEntity#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // MergeEntity
