/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Into External</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getMergeIntoExternal()
 * @model
 * @generated
 */
public interface MergeIntoExternal extends MergeEntity
{
} // MergeIntoExternal
