/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.Operations#getId <em>Id</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.Operations#getDocumentation <em>Documentation</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getOperations()
 * @model
 * @generated
 */
public interface Operations extends Statements
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getOperations_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.Operations#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Documentation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Documentation</em>' attribute.
   * @see #setDocumentation(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getOperations_Documentation()
   * @model
   * @generated
   */
  String getDocumentation();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.Operations#getDocumentation <em>Documentation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Documentation</em>' attribute.
   * @see #getDocumentation()
   * @generated
   */
  void setDocumentation(String value);

} // Operations
