/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Re ID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.ReID#getNewId <em>New Id</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getReID()
 * @model
 * @generated
 */
public interface ReID extends Modify
{
  /**
   * Returns the value of the '<em><b>New Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Id</em>' attribute.
   * @see #setNewId(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getReID_NewId()
   * @model
   * @generated
   */
  String getNewId();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.ReID#getNewId <em>New Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Id</em>' attribute.
   * @see #getNewId()
   * @generated
   */
  void setNewId(String value);

} // ReID
