/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getRemove()
 * @model
 * @generated
 */
public interface Remove extends Operations
{
} // Remove
