/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split Datastore And External</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitDatastoreAndExternal()
 * @model
 * @generated
 */
public interface SplitDatastoreAndExternal extends SplitEntity
{
} // SplitDatastoreAndExternal
