/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split External And Process</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitExternalAndProcess()
 * @model
 * @generated
 */
public interface SplitExternalAndProcess extends SplitEntity
{
} // SplitExternalAndProcess
