/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Splits Process And Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitsProcessAndDatastore()
 * @model
 * @generated
 */
public interface SplitsProcessAndDatastore extends SplitEntity
{
} // SplitsProcessAndDatastore
