/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity1 <em>Entity1</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity1Name <em>Entity1 Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity1Description <em>Entity1 Description</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity2Name <em>Entity2 Name</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getEntity2Description <em>Entity2 Description</em>}</li>
 *   <li>{@link xtext.threatModelLanguage.SplitEntity#getFlowFix <em>Flow Fix</em>}</li>
 * </ul>
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity()
 * @model
 * @generated
 */
public interface SplitEntity extends Modify
{
  /**
   * Returns the value of the '<em><b>Entity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity1</em>' attribute.
   * @see #setEntity1(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity1()
   * @model
   * @generated
   */
  String getEntity1();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity1 <em>Entity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity1</em>' attribute.
   * @see #getEntity1()
   * @generated
   */
  void setEntity1(String value);

  /**
   * Returns the value of the '<em><b>Entity1 Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity1 Name</em>' attribute.
   * @see #setEntity1Name(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity1Name()
   * @model
   * @generated
   */
  String getEntity1Name();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity1Name <em>Entity1 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity1 Name</em>' attribute.
   * @see #getEntity1Name()
   * @generated
   */
  void setEntity1Name(String value);

  /**
   * Returns the value of the '<em><b>Entity1 Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity1 Description</em>' attribute.
   * @see #setEntity1Description(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity1Description()
   * @model
   * @generated
   */
  String getEntity1Description();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity1Description <em>Entity1 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity1 Description</em>' attribute.
   * @see #getEntity1Description()
   * @generated
   */
  void setEntity1Description(String value);

  /**
   * Returns the value of the '<em><b>Entity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2</em>' attribute.
   * @see #setEntity2(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity2()
   * @model
   * @generated
   */
  String getEntity2();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity2 <em>Entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2</em>' attribute.
   * @see #getEntity2()
   * @generated
   */
  void setEntity2(String value);

  /**
   * Returns the value of the '<em><b>Entity2 Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2 Name</em>' attribute.
   * @see #setEntity2Name(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity2Name()
   * @model
   * @generated
   */
  String getEntity2Name();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity2Name <em>Entity2 Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2 Name</em>' attribute.
   * @see #getEntity2Name()
   * @generated
   */
  void setEntity2Name(String value);

  /**
   * Returns the value of the '<em><b>Entity2 Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2 Description</em>' attribute.
   * @see #setEntity2Description(String)
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_Entity2Description()
   * @model
   * @generated
   */
  String getEntity2Description();

  /**
   * Sets the value of the '{@link xtext.threatModelLanguage.SplitEntity#getEntity2Description <em>Entity2 Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2 Description</em>' attribute.
   * @see #getEntity2Description()
   * @generated
   */
  void setEntity2Description(String value);

  /**
   * Returns the value of the '<em><b>Flow Fix</b></em>' containment reference list.
   * The list contents are of type {@link xtext.threatModelLanguage.FlowFix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flow Fix</em>' containment reference list.
   * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitEntity_FlowFix()
   * @model containment="true"
   * @generated
   */
  EList<FlowFix> getFlowFix();

} // SplitEntity
