/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split External And Datastore</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getSplitExternalAndDatastore()
 * @model
 * @generated
 */
public interface SplitExternalAndDatastore extends SplitEntity
{
} // SplitExternalAndDatastore
