/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage#getStatements()
 * @model
 * @generated
 */
public interface Statements extends EObject
{
} // Statements
