/**
 * generated by Xtext 2.33.0
 */
package xtext.threatModelLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xtext.threatModelLanguage.ThreatModelLanguagePackage
 * @generated
 */
public interface ThreatModelLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ThreatModelLanguageFactory eINSTANCE = xtext.threatModelLanguage.impl.ThreatModelLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statements</em>'.
   * @generated
   */
  Statements createStatements();

  /**
   * Returns a new object of class '<em>Operations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operations</em>'.
   * @generated
   */
  Operations createOperations();

  /**
   * Returns a new object of class '<em>Add</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add</em>'.
   * @generated
   */
  Add createAdd();

  /**
   * Returns a new object of class '<em>Add Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Entity</em>'.
   * @generated
   */
  AddEntity createAddEntity();

  /**
   * Returns a new object of class '<em>Add Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Process</em>'.
   * @generated
   */
  AddProcess createAddProcess();

  /**
   * Returns a new object of class '<em>Add External</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add External</em>'.
   * @generated
   */
  AddExternal createAddExternal();

  /**
   * Returns a new object of class '<em>Add Datastore</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Datastore</em>'.
   * @generated
   */
  AddDatastore createAddDatastore();

  /**
   * Returns a new object of class '<em>Add Flow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Flow</em>'.
   * @generated
   */
  AddFlow createAddFlow();

  /**
   * Returns a new object of class '<em>Add Boundary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Boundary</em>'.
   * @generated
   */
  AddBoundary createAddBoundary();

  /**
   * Returns a new object of class '<em>Remove</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remove</em>'.
   * @generated
   */
  Remove createRemove();

  /**
   * Returns a new object of class '<em>Modify</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modify</em>'.
   * @generated
   */
  Modify createModify();

  /**
   * Returns a new object of class '<em>Rename</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rename</em>'.
   * @generated
   */
  Rename createRename();

  /**
   * Returns a new object of class '<em>Re ID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Re ID</em>'.
   * @generated
   */
  ReID createReID();

  /**
   * Returns a new object of class '<em>Change Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Change Description</em>'.
   * @generated
   */
  ChangeDescription createChangeDescription();

  /**
   * Returns a new object of class '<em>Flow Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow Source</em>'.
   * @generated
   */
  FlowSource createFlowSource();

  /**
   * Returns a new object of class '<em>Flow Destination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow Destination</em>'.
   * @generated
   */
  FlowDestination createFlowDestination();

  /**
   * Returns a new object of class '<em>Boundary Add Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boundary Add Entity</em>'.
   * @generated
   */
  BoundaryAddEntity createBoundaryAddEntity();

  /**
   * Returns a new object of class '<em>Boundary Remove Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boundary Remove Entity</em>'.
   * @generated
   */
  BoundaryRemoveEntity createBoundaryRemoveEntity();

  /**
   * Returns a new object of class '<em>Rotate Flow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotate Flow</em>'.
   * @generated
   */
  RotateFlow createRotateFlow();

  /**
   * Returns a new object of class '<em>Merge Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Merge Entity</em>'.
   * @generated
   */
  MergeEntity createMergeEntity();

  /**
   * Returns a new object of class '<em>Merge Into Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Merge Into Process</em>'.
   * @generated
   */
  MergeIntoProcess createMergeIntoProcess();

  /**
   * Returns a new object of class '<em>Merge Into External</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Merge Into External</em>'.
   * @generated
   */
  MergeIntoExternal createMergeIntoExternal();

  /**
   * Returns a new object of class '<em>Merge Into Datastore</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Merge Into Datastore</em>'.
   * @generated
   */
  MergeIntoDatastore createMergeIntoDatastore();

  /**
   * Returns a new object of class '<em>Split Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split Entity</em>'.
   * @generated
   */
  SplitEntity createSplitEntity();

  /**
   * Returns a new object of class '<em>Flow Fix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow Fix</em>'.
   * @generated
   */
  FlowFix createFlowFix();

  /**
   * Returns a new object of class '<em>Split Process And Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split Process And Process</em>'.
   * @generated
   */
  SplitProcessAndProcess createSplitProcessAndProcess();

  /**
   * Returns a new object of class '<em>Splits Process And Datastore</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Splits Process And Datastore</em>'.
   * @generated
   */
  SplitsProcessAndDatastore createSplitsProcessAndDatastore();

  /**
   * Returns a new object of class '<em>Splits Datastore And Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Splits Datastore And Process</em>'.
   * @generated
   */
  SplitsDatastoreAndProcess createSplitsDatastoreAndProcess();

  /**
   * Returns a new object of class '<em>Split Process And External</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split Process And External</em>'.
   * @generated
   */
  SplitProcessAndExternal createSplitProcessAndExternal();

  /**
   * Returns a new object of class '<em>Split External And Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split External And Process</em>'.
   * @generated
   */
  SplitExternalAndProcess createSplitExternalAndProcess();

  /**
   * Returns a new object of class '<em>Split Datastore And External</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split Datastore And External</em>'.
   * @generated
   */
  SplitDatastoreAndExternal createSplitDatastoreAndExternal();

  /**
   * Returns a new object of class '<em>Split External And Datastore</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split External And Datastore</em>'.
   * @generated
   */
  SplitExternalAndDatastore createSplitExternalAndDatastore();

  /**
   * Returns a new object of class '<em>Split Datastore And Datastore</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split Datastore And Datastore</em>'.
   * @generated
   */
  SplitDatastoreAndDatastore createSplitDatastoreAndDatastore();

  /**
   * Returns a new object of class '<em>Split External And External</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Split External And External</em>'.
   * @generated
   */
  SplitExternalAndExternal createSplitExternalAndExternal();

  /**
   * Returns a new object of class '<em>Grouping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Grouping</em>'.
   * @generated
   */
  Grouping createGrouping();

  /**
   * Returns a new object of class '<em>Countermeasure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Countermeasure</em>'.
   * @generated
   */
  Countermeasure createCountermeasure();

  /**
   * Returns a new object of class '<em>Design</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Design</em>'.
   * @generated
   */
  Design createDesign();

  /**
   * Returns a new object of class '<em>Refactoring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Refactoring</em>'.
   * @generated
   */
  Refactoring createRefactoring();

  /**
   * Returns a new object of class '<em>Testing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing</em>'.
   * @generated
   */
  Testing createTesting();

  /**
   * Returns a new object of class '<em>Sketching</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sketching</em>'.
   * @generated
   */
  Sketching createSketching();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ThreatModelLanguagePackage getThreatModelLanguagePackage();

} //ThreatModelLanguageFactory
