/*
 * generated by Xtext 2.33.0
 */
package xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xtext.ide.contentassist.antlr.internal.InternalThreatModelLanguageParser;
import xtext.services.ThreatModelLanguageGrammarAccess;

public class ThreatModelLanguageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ThreatModelLanguageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ThreatModelLanguageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementsAccess().getAlternatives(), "rule__Statements__Alternatives");
			builder.put(grammarAccess.getOperationsAccess().getAlternatives(), "rule__Operations__Alternatives");
			builder.put(grammarAccess.getAddAccess().getAlternatives(), "rule__Add__Alternatives");
			builder.put(grammarAccess.getAddEntityAccess().getAlternatives(), "rule__AddEntity__Alternatives");
			builder.put(grammarAccess.getModifyAccess().getAlternatives(), "rule__Modify__Alternatives");
			builder.put(grammarAccess.getMergeEntityAccess().getAlternatives(), "rule__MergeEntity__Alternatives");
			builder.put(grammarAccess.getSplitEntityAccess().getAlternatives(), "rule__SplitEntity__Alternatives");
			builder.put(grammarAccess.getGroupingAccess().getAlternatives(), "rule__Grouping__Alternatives");
			builder.put(grammarAccess.getAddProcessAccess().getGroup(), "rule__AddProcess__Group__0");
			builder.put(grammarAccess.getAddProcessAccess().getGroup_3(), "rule__AddProcess__Group_3__0");
			builder.put(grammarAccess.getAddProcessAccess().getGroup_4(), "rule__AddProcess__Group_4__0");
			builder.put(grammarAccess.getAddExternalAccess().getGroup(), "rule__AddExternal__Group__0");
			builder.put(grammarAccess.getAddExternalAccess().getGroup_4(), "rule__AddExternal__Group_4__0");
			builder.put(grammarAccess.getAddExternalAccess().getGroup_5(), "rule__AddExternal__Group_5__0");
			builder.put(grammarAccess.getAddDatastoreAccess().getGroup(), "rule__AddDatastore__Group__0");
			builder.put(grammarAccess.getAddDatastoreAccess().getGroup_3(), "rule__AddDatastore__Group_3__0");
			builder.put(grammarAccess.getAddDatastoreAccess().getGroup_4(), "rule__AddDatastore__Group_4__0");
			builder.put(grammarAccess.getAddFlowAccess().getGroup(), "rule__AddFlow__Group__0");
			builder.put(grammarAccess.getAddFlowAccess().getGroup_3(), "rule__AddFlow__Group_3__0");
			builder.put(grammarAccess.getAddFlowAccess().getGroup_4(), "rule__AddFlow__Group_4__0");
			builder.put(grammarAccess.getAddBoundaryAccess().getGroup(), "rule__AddBoundary__Group__0");
			builder.put(grammarAccess.getAddBoundaryAccess().getGroup_3(), "rule__AddBoundary__Group_3__0");
			builder.put(grammarAccess.getAddBoundaryAccess().getGroup_4(), "rule__AddBoundary__Group_4__0");
			builder.put(grammarAccess.getRemoveAccess().getGroup(), "rule__Remove__Group__0");
			builder.put(grammarAccess.getRenameAccess().getGroup(), "rule__Rename__Group__0");
			builder.put(grammarAccess.getReIDAccess().getGroup(), "rule__ReID__Group__0");
			builder.put(grammarAccess.getChangeDescriptionAccess().getGroup(), "rule__ChangeDescription__Group__0");
			builder.put(grammarAccess.getFlowSourceAccess().getGroup(), "rule__FlowSource__Group__0");
			builder.put(grammarAccess.getFlowDestinationAccess().getGroup(), "rule__FlowDestination__Group__0");
			builder.put(grammarAccess.getBoundaryAddEntityAccess().getGroup(), "rule__BoundaryAddEntity__Group__0");
			builder.put(grammarAccess.getBoundaryRemoveEntityAccess().getGroup(), "rule__BoundaryRemoveEntity__Group__0");
			builder.put(grammarAccess.getRotateFlowAccess().getGroup(), "rule__RotateFlow__Group__0");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getGroup(), "rule__MergeIntoProcess__Group__0");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getGroup_7(), "rule__MergeIntoProcess__Group_7__0");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getGroup_8(), "rule__MergeIntoProcess__Group_8__0");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getGroup(), "rule__MergeIntoExternal__Group__0");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getGroup_8(), "rule__MergeIntoExternal__Group_8__0");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getGroup_9(), "rule__MergeIntoExternal__Group_9__0");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getGroup(), "rule__MergeIntoDatastore__Group__0");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getGroup_7(), "rule__MergeIntoDatastore__Group_7__0");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getGroup_8(), "rule__MergeIntoDatastore__Group_8__0");
			builder.put(grammarAccess.getFlowFixAccess().getGroup(), "rule__FlowFix__Group__0");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getGroup(), "rule__SplitProcessAndProcess__Group__0");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getGroup_5(), "rule__SplitProcessAndProcess__Group_5__0");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getGroup_6(), "rule__SplitProcessAndProcess__Group_6__0");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getGroup_10(), "rule__SplitProcessAndProcess__Group_10__0");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getGroup_11(), "rule__SplitProcessAndProcess__Group_11__0");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getGroup(), "rule__SplitsProcessAndDatastore__Group__0");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getGroup_5(), "rule__SplitsProcessAndDatastore__Group_5__0");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getGroup_6(), "rule__SplitsProcessAndDatastore__Group_6__0");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getGroup_10(), "rule__SplitsProcessAndDatastore__Group_10__0");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getGroup_11(), "rule__SplitsProcessAndDatastore__Group_11__0");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getGroup(), "rule__SplitsDatastoreAndProcess__Group__0");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getGroup_5(), "rule__SplitsDatastoreAndProcess__Group_5__0");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getGroup_6(), "rule__SplitsDatastoreAndProcess__Group_6__0");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getGroup_10(), "rule__SplitsDatastoreAndProcess__Group_10__0");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getGroup_11(), "rule__SplitsDatastoreAndProcess__Group_11__0");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getGroup(), "rule__SplitProcessAndExternal__Group__0");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getGroup_5(), "rule__SplitProcessAndExternal__Group_5__0");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getGroup_6(), "rule__SplitProcessAndExternal__Group_6__0");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getGroup_11(), "rule__SplitProcessAndExternal__Group_11__0");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getGroup_12(), "rule__SplitProcessAndExternal__Group_12__0");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getGroup(), "rule__SplitExternalAndProcess__Group__0");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getGroup_6(), "rule__SplitExternalAndProcess__Group_6__0");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getGroup_7(), "rule__SplitExternalAndProcess__Group_7__0");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getGroup_11(), "rule__SplitExternalAndProcess__Group_11__0");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getGroup_12(), "rule__SplitExternalAndProcess__Group_12__0");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getGroup(), "rule__SplitDatastoreAndExternal__Group__0");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getGroup_5(), "rule__SplitDatastoreAndExternal__Group_5__0");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getGroup_6(), "rule__SplitDatastoreAndExternal__Group_6__0");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getGroup_11(), "rule__SplitDatastoreAndExternal__Group_11__0");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getGroup_12(), "rule__SplitDatastoreAndExternal__Group_12__0");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getGroup(), "rule__SplitExternalAndDatastore__Group__0");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getGroup_6(), "rule__SplitExternalAndDatastore__Group_6__0");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getGroup_7(), "rule__SplitExternalAndDatastore__Group_7__0");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getGroup_11(), "rule__SplitExternalAndDatastore__Group_11__0");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getGroup_12(), "rule__SplitExternalAndDatastore__Group_12__0");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getGroup(), "rule__SplitDatastoreAndDatastore__Group__0");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getGroup_5(), "rule__SplitDatastoreAndDatastore__Group_5__0");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getGroup_6(), "rule__SplitDatastoreAndDatastore__Group_6__0");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getGroup_10(), "rule__SplitDatastoreAndDatastore__Group_10__0");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getGroup_11(), "rule__SplitDatastoreAndDatastore__Group_11__0");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getGroup(), "rule__SplitExternalAndExternal__Group__0");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getGroup_6(), "rule__SplitExternalAndExternal__Group_6__0");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getGroup_7(), "rule__SplitExternalAndExternal__Group_7__0");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getGroup_12(), "rule__SplitExternalAndExternal__Group_12__0");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getGroup_13(), "rule__SplitExternalAndExternal__Group_13__0");
			builder.put(grammarAccess.getCountermeasureAccess().getGroup(), "rule__Countermeasure__Group__0");
			builder.put(grammarAccess.getDesignAccess().getGroup(), "rule__Design__Group__0");
			builder.put(grammarAccess.getRefactoringAccess().getGroup(), "rule__Refactoring__Group__0");
			builder.put(grammarAccess.getTestingAccess().getGroup(), "rule__Testing__Group__0");
			builder.put(grammarAccess.getSketchingAccess().getGroup(), "rule__Sketching__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getAddProcessAccess().getIdAssignment_2(), "rule__AddProcess__IdAssignment_2");
			builder.put(grammarAccess.getAddProcessAccess().getNameAssignment_3_1(), "rule__AddProcess__NameAssignment_3_1");
			builder.put(grammarAccess.getAddProcessAccess().getDescriptionAssignment_4_1(), "rule__AddProcess__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAddProcessAccess().getDocumentationAssignment_5(), "rule__AddProcess__DocumentationAssignment_5");
			builder.put(grammarAccess.getAddExternalAccess().getIdAssignment_3(), "rule__AddExternal__IdAssignment_3");
			builder.put(grammarAccess.getAddExternalAccess().getNameAssignment_4_1(), "rule__AddExternal__NameAssignment_4_1");
			builder.put(grammarAccess.getAddExternalAccess().getDescriptionAssignment_5_1(), "rule__AddExternal__DescriptionAssignment_5_1");
			builder.put(grammarAccess.getAddExternalAccess().getDocumentationAssignment_6(), "rule__AddExternal__DocumentationAssignment_6");
			builder.put(grammarAccess.getAddDatastoreAccess().getIdAssignment_2(), "rule__AddDatastore__IdAssignment_2");
			builder.put(grammarAccess.getAddDatastoreAccess().getNameAssignment_3_1(), "rule__AddDatastore__NameAssignment_3_1");
			builder.put(grammarAccess.getAddDatastoreAccess().getDescriptionAssignment_4_1(), "rule__AddDatastore__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAddDatastoreAccess().getDocumentationAssignment_5(), "rule__AddDatastore__DocumentationAssignment_5");
			builder.put(grammarAccess.getAddFlowAccess().getIdAssignment_2(), "rule__AddFlow__IdAssignment_2");
			builder.put(grammarAccess.getAddFlowAccess().getNameAssignment_3_1(), "rule__AddFlow__NameAssignment_3_1");
			builder.put(grammarAccess.getAddFlowAccess().getDescriptionAssignment_4_1(), "rule__AddFlow__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAddFlowAccess().getSourceIdAssignment_5(), "rule__AddFlow__SourceIdAssignment_5");
			builder.put(grammarAccess.getAddFlowAccess().getDestinationIdAssignment_7(), "rule__AddFlow__DestinationIdAssignment_7");
			builder.put(grammarAccess.getAddFlowAccess().getDocumentationAssignment_8(), "rule__AddFlow__DocumentationAssignment_8");
			builder.put(grammarAccess.getAddBoundaryAccess().getIdAssignment_2(), "rule__AddBoundary__IdAssignment_2");
			builder.put(grammarAccess.getAddBoundaryAccess().getNameAssignment_3_1(), "rule__AddBoundary__NameAssignment_3_1");
			builder.put(grammarAccess.getAddBoundaryAccess().getDescriptionAssignment_4_1(), "rule__AddBoundary__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAddBoundaryAccess().getEntitiesAssignment_6(), "rule__AddBoundary__EntitiesAssignment_6");
			builder.put(grammarAccess.getAddBoundaryAccess().getDocumentationAssignment_7(), "rule__AddBoundary__DocumentationAssignment_7");
			builder.put(grammarAccess.getRemoveAccess().getIdAssignment_1(), "rule__Remove__IdAssignment_1");
			builder.put(grammarAccess.getRemoveAccess().getDocumentationAssignment_2(), "rule__Remove__DocumentationAssignment_2");
			builder.put(grammarAccess.getRenameAccess().getIdAssignment_1(), "rule__Rename__IdAssignment_1");
			builder.put(grammarAccess.getRenameAccess().getNewNameAssignment_3(), "rule__Rename__NewNameAssignment_3");
			builder.put(grammarAccess.getRenameAccess().getDocumentationAssignment_4(), "rule__Rename__DocumentationAssignment_4");
			builder.put(grammarAccess.getReIDAccess().getIdAssignment_1(), "rule__ReID__IdAssignment_1");
			builder.put(grammarAccess.getReIDAccess().getNewIdAssignment_3(), "rule__ReID__NewIdAssignment_3");
			builder.put(grammarAccess.getReIDAccess().getDocumentationAssignment_4(), "rule__ReID__DocumentationAssignment_4");
			builder.put(grammarAccess.getChangeDescriptionAccess().getIdAssignment_1(), "rule__ChangeDescription__IdAssignment_1");
			builder.put(grammarAccess.getChangeDescriptionAccess().getDescriptionAssignment_3(), "rule__ChangeDescription__DescriptionAssignment_3");
			builder.put(grammarAccess.getChangeDescriptionAccess().getDocumentationAssignment_4(), "rule__ChangeDescription__DocumentationAssignment_4");
			builder.put(grammarAccess.getFlowSourceAccess().getIdAssignment_1(), "rule__FlowSource__IdAssignment_1");
			builder.put(grammarAccess.getFlowSourceAccess().getSourceAssignment_3(), "rule__FlowSource__SourceAssignment_3");
			builder.put(grammarAccess.getFlowSourceAccess().getDocumentationAssignment_4(), "rule__FlowSource__DocumentationAssignment_4");
			builder.put(grammarAccess.getFlowDestinationAccess().getIdAssignment_1(), "rule__FlowDestination__IdAssignment_1");
			builder.put(grammarAccess.getFlowDestinationAccess().getDestinationAssignment_3(), "rule__FlowDestination__DestinationAssignment_3");
			builder.put(grammarAccess.getFlowDestinationAccess().getDocumentationAssignment_4(), "rule__FlowDestination__DocumentationAssignment_4");
			builder.put(grammarAccess.getBoundaryAddEntityAccess().getIdAssignment_1(), "rule__BoundaryAddEntity__IdAssignment_1");
			builder.put(grammarAccess.getBoundaryAddEntityAccess().getNewEntityAssignment_3(), "rule__BoundaryAddEntity__NewEntityAssignment_3");
			builder.put(grammarAccess.getBoundaryAddEntityAccess().getDocumentationAssignment_4(), "rule__BoundaryAddEntity__DocumentationAssignment_4");
			builder.put(grammarAccess.getBoundaryRemoveEntityAccess().getIdAssignment_1(), "rule__BoundaryRemoveEntity__IdAssignment_1");
			builder.put(grammarAccess.getBoundaryRemoveEntityAccess().getOldEntityAssignment_3(), "rule__BoundaryRemoveEntity__OldEntityAssignment_3");
			builder.put(grammarAccess.getBoundaryRemoveEntityAccess().getDocumentationAssignment_4(), "rule__BoundaryRemoveEntity__DocumentationAssignment_4");
			builder.put(grammarAccess.getRotateFlowAccess().getIdAssignment_1(), "rule__RotateFlow__IdAssignment_1");
			builder.put(grammarAccess.getRotateFlowAccess().getDocumentationAssignment_4(), "rule__RotateFlow__DocumentationAssignment_4");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getEntity1Assignment_1(), "rule__MergeIntoProcess__Entity1Assignment_1");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getEntity2Assignment_3(), "rule__MergeIntoProcess__Entity2Assignment_3");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getIdAssignment_6(), "rule__MergeIntoProcess__IdAssignment_6");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getNameAssignment_7_1(), "rule__MergeIntoProcess__NameAssignment_7_1");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getDescriptionAssignment_8_1(), "rule__MergeIntoProcess__DescriptionAssignment_8_1");
			builder.put(grammarAccess.getMergeIntoProcessAccess().getDocumentationAssignment_9(), "rule__MergeIntoProcess__DocumentationAssignment_9");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getEntity1Assignment_1(), "rule__MergeIntoExternal__Entity1Assignment_1");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getEntity2Assignment_3(), "rule__MergeIntoExternal__Entity2Assignment_3");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getIdAssignment_7(), "rule__MergeIntoExternal__IdAssignment_7");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getNameAssignment_8_1(), "rule__MergeIntoExternal__NameAssignment_8_1");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getDescriptionAssignment_9_1(), "rule__MergeIntoExternal__DescriptionAssignment_9_1");
			builder.put(grammarAccess.getMergeIntoExternalAccess().getDocumentationAssignment_10(), "rule__MergeIntoExternal__DocumentationAssignment_10");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getEntity1Assignment_1(), "rule__MergeIntoDatastore__Entity1Assignment_1");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getEntity2Assignment_3(), "rule__MergeIntoDatastore__Entity2Assignment_3");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getIdAssignment_6(), "rule__MergeIntoDatastore__IdAssignment_6");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getNameAssignment_7_1(), "rule__MergeIntoDatastore__NameAssignment_7_1");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getDescriptionAssignment_8_1(), "rule__MergeIntoDatastore__DescriptionAssignment_8_1");
			builder.put(grammarAccess.getMergeIntoDatastoreAccess().getDocumentationAssignment_9(), "rule__MergeIntoDatastore__DocumentationAssignment_9");
			builder.put(grammarAccess.getFlowFixAccess().getFlowIdAssignment_0(), "rule__FlowFix__FlowIdAssignment_0");
			builder.put(grammarAccess.getFlowFixAccess().getEntityIdAssignment_2(), "rule__FlowFix__EntityIdAssignment_2");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getIdAssignment_1(), "rule__SplitProcessAndProcess__IdAssignment_1");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity1Assignment_4(), "rule__SplitProcessAndProcess__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity1NameAssignment_5_1(), "rule__SplitProcessAndProcess__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitProcessAndProcess__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity2Assignment_9(), "rule__SplitProcessAndProcess__Entity2Assignment_9");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity2NameAssignment_10_1(), "rule__SplitProcessAndProcess__Entity2NameAssignment_10_1");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getEntity2DescriptionAssignment_11_1(), "rule__SplitProcessAndProcess__Entity2DescriptionAssignment_11_1");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getFlowFixAssignment_14(), "rule__SplitProcessAndProcess__FlowFixAssignment_14");
			builder.put(grammarAccess.getSplitProcessAndProcessAccess().getDocumentationAssignment_16(), "rule__SplitProcessAndProcess__DocumentationAssignment_16");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getIdAssignment_1(), "rule__SplitsProcessAndDatastore__IdAssignment_1");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity1Assignment_4(), "rule__SplitsProcessAndDatastore__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity1NameAssignment_5_1(), "rule__SplitsProcessAndDatastore__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitsProcessAndDatastore__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity2Assignment_9(), "rule__SplitsProcessAndDatastore__Entity2Assignment_9");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity2NameAssignment_10_1(), "rule__SplitsProcessAndDatastore__Entity2NameAssignment_10_1");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getEntity2DescriptionAssignment_11_1(), "rule__SplitsProcessAndDatastore__Entity2DescriptionAssignment_11_1");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getFlowFixAssignment_14(), "rule__SplitsProcessAndDatastore__FlowFixAssignment_14");
			builder.put(grammarAccess.getSplitsProcessAndDatastoreAccess().getDocumentationAssignment_16(), "rule__SplitsProcessAndDatastore__DocumentationAssignment_16");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getIdAssignment_1(), "rule__SplitsDatastoreAndProcess__IdAssignment_1");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity1Assignment_4(), "rule__SplitsDatastoreAndProcess__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity1NameAssignment_5_1(), "rule__SplitsDatastoreAndProcess__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitsDatastoreAndProcess__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity2Assignment_9(), "rule__SplitsDatastoreAndProcess__Entity2Assignment_9");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity2NameAssignment_10_1(), "rule__SplitsDatastoreAndProcess__Entity2NameAssignment_10_1");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getEntity2DescriptionAssignment_11_1(), "rule__SplitsDatastoreAndProcess__Entity2DescriptionAssignment_11_1");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getFlowFixAssignment_14(), "rule__SplitsDatastoreAndProcess__FlowFixAssignment_14");
			builder.put(grammarAccess.getSplitsDatastoreAndProcessAccess().getDocumentationAssignment_16(), "rule__SplitsDatastoreAndProcess__DocumentationAssignment_16");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getIdAssignment_1(), "rule__SplitProcessAndExternal__IdAssignment_1");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity1Assignment_4(), "rule__SplitProcessAndExternal__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity1NameAssignment_5_1(), "rule__SplitProcessAndExternal__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitProcessAndExternal__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity2Assignment_10(), "rule__SplitProcessAndExternal__Entity2Assignment_10");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity2NameAssignment_11_1(), "rule__SplitProcessAndExternal__Entity2NameAssignment_11_1");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getEntity2DescriptionAssignment_12_1(), "rule__SplitProcessAndExternal__Entity2DescriptionAssignment_12_1");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getFlowFixAssignment_15(), "rule__SplitProcessAndExternal__FlowFixAssignment_15");
			builder.put(grammarAccess.getSplitProcessAndExternalAccess().getDocumentationAssignment_17(), "rule__SplitProcessAndExternal__DocumentationAssignment_17");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getIdAssignment_1(), "rule__SplitExternalAndProcess__IdAssignment_1");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity1Assignment_5(), "rule__SplitExternalAndProcess__Entity1Assignment_5");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity1NameAssignment_6_1(), "rule__SplitExternalAndProcess__Entity1NameAssignment_6_1");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity1DescriptionAssignment_7_1(), "rule__SplitExternalAndProcess__Entity1DescriptionAssignment_7_1");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity2Assignment_10(), "rule__SplitExternalAndProcess__Entity2Assignment_10");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity2NameAssignment_11_1(), "rule__SplitExternalAndProcess__Entity2NameAssignment_11_1");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getEntity2DescriptionAssignment_12_1(), "rule__SplitExternalAndProcess__Entity2DescriptionAssignment_12_1");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getFlowFixAssignment_15(), "rule__SplitExternalAndProcess__FlowFixAssignment_15");
			builder.put(grammarAccess.getSplitExternalAndProcessAccess().getDocumentationAssignment_17(), "rule__SplitExternalAndProcess__DocumentationAssignment_17");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getIdAssignment_1(), "rule__SplitDatastoreAndExternal__IdAssignment_1");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity1Assignment_4(), "rule__SplitDatastoreAndExternal__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity1NameAssignment_5_1(), "rule__SplitDatastoreAndExternal__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitDatastoreAndExternal__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity2Assignment_10(), "rule__SplitDatastoreAndExternal__Entity2Assignment_10");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity2NameAssignment_11_1(), "rule__SplitDatastoreAndExternal__Entity2NameAssignment_11_1");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getEntity2DescriptionAssignment_12_1(), "rule__SplitDatastoreAndExternal__Entity2DescriptionAssignment_12_1");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getFlowFixAssignment_15(), "rule__SplitDatastoreAndExternal__FlowFixAssignment_15");
			builder.put(grammarAccess.getSplitDatastoreAndExternalAccess().getDocumentationAssignment_17(), "rule__SplitDatastoreAndExternal__DocumentationAssignment_17");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getIdAssignment_1(), "rule__SplitExternalAndDatastore__IdAssignment_1");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity1Assignment_5(), "rule__SplitExternalAndDatastore__Entity1Assignment_5");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity1NameAssignment_6_1(), "rule__SplitExternalAndDatastore__Entity1NameAssignment_6_1");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity1DescriptionAssignment_7_1(), "rule__SplitExternalAndDatastore__Entity1DescriptionAssignment_7_1");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity2Assignment_10(), "rule__SplitExternalAndDatastore__Entity2Assignment_10");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity2NameAssignment_11_1(), "rule__SplitExternalAndDatastore__Entity2NameAssignment_11_1");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getEntity2DescriptionAssignment_12_1(), "rule__SplitExternalAndDatastore__Entity2DescriptionAssignment_12_1");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getFlowFixAssignment_15(), "rule__SplitExternalAndDatastore__FlowFixAssignment_15");
			builder.put(grammarAccess.getSplitExternalAndDatastoreAccess().getDocumentationAssignment_17(), "rule__SplitExternalAndDatastore__DocumentationAssignment_17");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getIdAssignment_1(), "rule__SplitDatastoreAndDatastore__IdAssignment_1");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity1Assignment_4(), "rule__SplitDatastoreAndDatastore__Entity1Assignment_4");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity1NameAssignment_5_1(), "rule__SplitDatastoreAndDatastore__Entity1NameAssignment_5_1");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity1DescriptionAssignment_6_1(), "rule__SplitDatastoreAndDatastore__Entity1DescriptionAssignment_6_1");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity2Assignment_9(), "rule__SplitDatastoreAndDatastore__Entity2Assignment_9");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity2NameAssignment_10_1(), "rule__SplitDatastoreAndDatastore__Entity2NameAssignment_10_1");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getEntity2DescriptionAssignment_11_1(), "rule__SplitDatastoreAndDatastore__Entity2DescriptionAssignment_11_1");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getFlowFixAssignment_14(), "rule__SplitDatastoreAndDatastore__FlowFixAssignment_14");
			builder.put(grammarAccess.getSplitDatastoreAndDatastoreAccess().getDocumentationAssignment_16(), "rule__SplitDatastoreAndDatastore__DocumentationAssignment_16");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getIdAssignment_1(), "rule__SplitExternalAndExternal__IdAssignment_1");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity1Assignment_5(), "rule__SplitExternalAndExternal__Entity1Assignment_5");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity1NameAssignment_6_1(), "rule__SplitExternalAndExternal__Entity1NameAssignment_6_1");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity1DescriptionAssignment_7_1(), "rule__SplitExternalAndExternal__Entity1DescriptionAssignment_7_1");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity2Assignment_11(), "rule__SplitExternalAndExternal__Entity2Assignment_11");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity2NameAssignment_12_1(), "rule__SplitExternalAndExternal__Entity2NameAssignment_12_1");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getEntity2DescriptionAssignment_13_1(), "rule__SplitExternalAndExternal__Entity2DescriptionAssignment_13_1");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getFlowFixAssignment_16(), "rule__SplitExternalAndExternal__FlowFixAssignment_16");
			builder.put(grammarAccess.getSplitExternalAndExternalAccess().getDocumentationAssignment_18(), "rule__SplitExternalAndExternal__DocumentationAssignment_18");
			builder.put(grammarAccess.getCountermeasureAccess().getNameAssignment_1(), "rule__Countermeasure__NameAssignment_1");
			builder.put(grammarAccess.getCountermeasureAccess().getDescriptionAssignment_2(), "rule__Countermeasure__DescriptionAssignment_2");
			builder.put(grammarAccess.getCountermeasureAccess().getOperatoinsAssignment_4(), "rule__Countermeasure__OperatoinsAssignment_4");
			builder.put(grammarAccess.getDesignAccess().getNameAssignment_1(), "rule__Design__NameAssignment_1");
			builder.put(grammarAccess.getDesignAccess().getDescriptionAssignment_2(), "rule__Design__DescriptionAssignment_2");
			builder.put(grammarAccess.getDesignAccess().getOperatoinsAssignment_4(), "rule__Design__OperatoinsAssignment_4");
			builder.put(grammarAccess.getRefactoringAccess().getNameAssignment_1(), "rule__Refactoring__NameAssignment_1");
			builder.put(grammarAccess.getRefactoringAccess().getDescriptionAssignment_2(), "rule__Refactoring__DescriptionAssignment_2");
			builder.put(grammarAccess.getRefactoringAccess().getOperatoinsAssignment_4(), "rule__Refactoring__OperatoinsAssignment_4");
			builder.put(grammarAccess.getTestingAccess().getNameAssignment_1(), "rule__Testing__NameAssignment_1");
			builder.put(grammarAccess.getTestingAccess().getDescriptionAssignment_2(), "rule__Testing__DescriptionAssignment_2");
			builder.put(grammarAccess.getTestingAccess().getOperatoinsAssignment_4(), "rule__Testing__OperatoinsAssignment_4");
			builder.put(grammarAccess.getSketchingAccess().getNameAssignment_1(), "rule__Sketching__NameAssignment_1");
			builder.put(grammarAccess.getSketchingAccess().getDescriptionAssignment_2(), "rule__Sketching__DescriptionAssignment_2");
			builder.put(grammarAccess.getSketchingAccess().getOperatoinsAssignment_4(), "rule__Sketching__OperatoinsAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ThreatModelLanguageGrammarAccess grammarAccess;

	@Override
	protected InternalThreatModelLanguageParser createParser() {
		InternalThreatModelLanguageParser result = new InternalThreatModelLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ThreatModelLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThreatModelLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
