/*
 * generated by Xtext 2.33.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ThreatModelLanguageStandaloneSetup extends ThreatModelLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new ThreatModelLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
