/*
 * generated by Xtext 2.33.0
 */
package xtext;

import org.eclipse.xtext.validation.IResourceValidator;

import xtext.validation.ThreatModelLanguageValidator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ThreatModelLanguageRuntimeModule extends AbstractThreatModelLanguageRuntimeModule {

	/*
	public Class<? extends IResourceValidator> bindIResourceValidator() {
        return (Class<? extends IResourceValidator>) ThreatModelLanguageValidator.class;
    }
    */
}
