/*
 * generated by Xtext 2.33.0
 */
package xtext.ide;


/**
 * Use this class to register ide components.
 */
public class ThreatModelLanguageIdeModule extends AbstractThreatModelLanguageIdeModule {
}
