/*
 * generated by Xtext 2.33.0
 */
package xtext.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ThreatModelLanguageProposalProvider extends AbstractThreatModelLanguageProposalProvider {
}
