/*
 * generated by Xtext 2.33.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalThreatModelLanguageParser;
import xtext.services.ThreatModelLanguageGrammarAccess;

public class ThreatModelLanguageParser extends AbstractAntlrParser {

	@Inject
	private ThreatModelLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalThreatModelLanguageParser createParser(XtextTokenStream stream) {
		return new InternalThreatModelLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ThreatModelLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThreatModelLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
